### ISSUE TITLE
Write an abstract

### ISSUE THREAD

**Issue by JJ** [analca3/IJCCI-2017#12]
The abstract is the general layout of the argument you are going to present in the paper. It is almost impossible to write a paper without having the abstract first.

**Comment by 29antonioac** [comment]
Is it ok now? Do you think is it too detailed?

**Comment by 29antonioac** [comment]
ATM the abstract has 244 words, and the maximum is 200. Should we delete some introduction? 

In the file, first paragraph has 157 words and the second one 87.

**Comment by JJ** [comment]
We can worry about that if the paper is accepted. If you rephrase,
eliminate iterations and things like that.

**Comment by 29antonioac** [comment]
Ok
