### ISSUE TITLE
More authors

### ISSUE THREAD

**Issue by 29antonioac** [analca3/IJCCI-2017#14]
I think @fergunet and @deantares should be co-authors, too. They were a big support in this work.

If you want, send me your information and I'll add them.

**Comment by JJ** [comment]
Sure!

**Comment by fergunet** [comment]
Thank you very much @analca3 !!! 

My information is: Pablo García Sánchez, Dept. of Computer Science, ESI, University of Cádiz, Avda. de la Universidad de Cádiz, Puerto Real, Cádiz. pablo.garciasanchez@uca.es

I will try to review the paper if I'm bored in my trip to NY (but I can't promise it at all... ;P )

**Comment by deantares** [comment]
I already talked with you in telegram. Thank you very much! I will try to read it today.

My information: Antonio Fernández Ares (A.Fernández-Ares), }Department of Computer Architecture and Computer Technology, University of Granada, Spain, antares@ugr.es
