### ISSUE TITLE
What topics should we select?

### ISSUE THREAD

**Issue by 29antonioac** [analca3/IJCCI-2017#15]
I think this would be a good choice

![image](https://user-images.githubusercontent.com/3939991/30035272-a6f51b8e-91a8-11e7-9dde-d7bb388335d0.png)

What do you think, @JJ ?

**Comment by JJ** [comment]
I guess it's OK, but I would like to have another look at everything, as
well as give @antareses and @fergunet a chance to review it... You can
always update.
Other than that, good job.

**Comment by 29antonioac** [comment]
Antares have reviewed it :)

If you want to review it, ok, but the deadline is in a few hours.



El 4 sept. 2017 21:19, "Juan Julián Merelo Guervós" <
notifications@github.com> escribió:

I guess it's OK, but I would like to have another look at everything, as
well as give @antareses and @fergunet a chance to review it... You can
always update.
Other than that, good job.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/analca3/IJCCI-2017/issues/15#issuecomment-327017616>,
or mute the thread

**Comment by JJ** [comment]
2017-09-04 21:27 GMT+02:00 Antonio Álvarez Caballero <
notifications@github.com>:

> Antares have reviewed it :)
>
> If you want to review it, ok, but the deadline is in a few hours.
>

Didn't know, sorry. And @fergunet probably won't. And I don't have time.
OK, let's see if I can do somerhing ad we'll resend. Still, it does not
hurt to pass again a spell checker and try to catch grammar and other kind
of errors.
