### ISSUE TITLE
Describe the objective of the paper

### ISSUE THREAD

**Issue by JJ** [analca3/IJCCI-2017#8]
The first thing in a paper is the set of objectives, the "selling points" or point. This paper should publish the results of the Degree's thesis and advance the results of the Master's thesis

**Comment by 29antonioac** [comment]
There are inside the introduction section, as you said me in the other repo. Please check this out

https://github.com/analca3/IJCCI-2017/blob/master/Prediction.Rnw#L88

If there are some mistakes, please let me know
